title: "on [...]"
description: "Cole Christini's Personal Website"
subtitle: ""
author: Cole Christini


theme: jekyll-theme-tufte
markdown: kramdown

plugins:
  - jekyll-theme-tufte
  # - jekyll-feed
  # - jekyll-seo-tag

# Optional
# permalink: /:title/
